token_dist/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from . import views
from django.contrib.auth.views import LoginView , LogoutView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='index'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('dashboard/user', views.account_settings, name='account_settings'),
    path('dashboard/update_password', views.update_password, name='update_password'),
    path('dashboard/delete_user ',views.delete_user, name="delete_user"),
    path('events/', views.events, name='events'),
    path('login/', LoginView.as_view(redirect_authenticated_user=True) , name='login'),
    path('logout/', LogoutView.as_view() , name='logout'),
    path('tokens/',include('tokens.urls', namespace='tokens')),
    path('event/<int:pk>',views.event, name="event_details"),
    path('event/studentlist/<int:pk>',views.event_stulist, name="studentlist"),
    path('event_update/',views.event_update, name="event_update"),
    path('delete_event/',views.delete_event, name="delete_event"),
    path('create_user/',views.create_user, name="create_user"),
    path('create_event/',views.create_event, name="create_event"),
    path('create_user_post/',views.create_user_post, name="create_user_post"),
]

urlpatterns += static(settings.STATIC_URL , document_root=settings.STATIC_ROOT)


handler404 = views.handle_page_not_found
handler500 = views.handle_server_error
handler400 = views.handle_bad_request

tokens/urls.py
from django.urls import path
from . import views

app_name = 'tokens'

urlpatterns = [
    path('event/<int:pk>', views.token, name='token_event'),
    path('print_token/<int:num>/<int:pk>', views.print_token, name='print_token'),
    path('generate_tokens/', views.generate_tokens, name='generate_tokens'),
    path('update_print_status/', views.update_print_status, name='update_print_status'),
    path('scanner_dist/<int:pk>', views.scanner_dist, name='scanner_dist'),
    path('scanner_receive/<int:pk>', views.scanner_receive, name='scanner_receive'),
    path('token_activate/', views.token_activate, name='token_activate'),
    path('token_activate_new/', views.token_activate_new, name='token_activate_new'),
    path('token_receive/', views.token_receive, name='token_receive'),
]

tokens/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _
from django.utils.timezone import now  

class Event(models.Model):
    name = models.CharField(_("Event"),max_length=50,null=True,blank=True)
    created_date = models.DateTimeField(default=now)
    event_date = models.DateTimeField(_("Event Date"),null=True,blank=True)
    token_dist_start = models.DateTimeField(_("Token Distribution Start"),null=True,blank=True)
    token_dist_end = models.DateTimeField(_("Token Distribution End"),null=True,blank=True)
    token_usage = models.IntegerField(_("Token Usage Limit"),default=0)
    # tags = models.ManyToManyField(Tag,blank=True)
    distribution_place = models.CharField(_("Distribution"),max_length=100,null=True,blank=True)
    desc = models.TextField(_("Description"),null=True,blank=True)

    def __str__(self):
        return self.name
    
    @property
    def get_tokens(self):
        tokens = self.token_set.all()
        return tokens  
    
    @property
    def get_tokens_non_printed_count(self):
        tokens = self.token_set.filter(is_printed=False).count()
        return tokens  
    
    @property
    def get_printed_tokens(self):
        tokens = self.token_set.filter(is_printed=True)
        return tokens  
    
    @property
    def get_activated_tokens(self):
        tokens = self.token_set.filter(is_activated=True)
        return tokens  

class Token(models.Model):
    id = models.BigAutoField(primary_key=True,editable=False)
    event = models.ForeignKey(Event,verbose_name=_("Event"),on_delete=models.CASCADE,null=True,blank=True)
    token_serial = models.CharField(_("Serial"),max_length=20,null=True,blank=True)
    is_printed = models.BooleanField(_("Printed"),default=False)
    is_activated = models.BooleanField(_("Activated"),default=False)
    entry_flag = models.BooleanField(_("Entry Status"),default=False,null=True,blank=True)
    food_flag = models.BooleanField(_("Food Status"),default=False,null=True,blank=True)
    student_id = models.CharField(_("Student Id"),max_length=8,null=True,blank=True)

    class Meta:
        verbose_name_plural = "Tokens"
    
    def __str__(self):
        return f'{self.event} - {self.id} - {self.token_serial}'
    

class StudentList(models.Model):
    student_id = models.CharField(_("Student Id"),max_length=8,null=True, blank=True)
    name = models.CharField(_("Name"),max_length=50,null=True,blank=True)
    event = models.ForeignKey(Event,verbose_name=_("Event"),on_delete=models.CASCADE,null=True,blank=True)
    claimed = models.BooleanField(_("Token Claimed"),default=False,null=True,blank=True)
    
    class Meta:
        verbose_name_plural = "Student List"
    
    def __str__(self):
        return f'{self.student_id} for - {self.event}'

tokens/views.py
import math
import json

from django.shortcuts import render
from django.http import JsonResponse, HttpResponse
from django.utils.timezone import now
from django.contrib.auth.decorators import login_required

from token_dist.decorators import admin_access
from .models import Token, Event, StudentList

# Create your views here.
@admin_access
def token(request, pk):
    event = Event.objects.get(id=pk)

    end_event = event.event_date
    end_event = int(end_event.strftime('%Y%m%d%H%M'))

    current_date = now()
    current_date = int(current_date.strftime('%Y%m%d%H%M'))

    if current_date > end_event:
        return HttpResponse("This event has already finished. To generate tokens please consider changing event date from event management page. Thanks.")
    context = {
        "event": event,
    }
    return render(request, "tokens.html", context)

@admin_access
def print_token(request, num, pk):
    event = Event.objects.get(id=pk)
    count = event.get_tokens_non_printed_count
    if num > count:
        num = count
    tokens = event.token_set.filter(is_printed=False)[:num]
    token_index = []

    total_pgs = math.ceil(num/10)


    try:
        st = int(tokens[0].token_serial[8:])
        last_ck = int(tokens[num-1].token_serial[8:])
        start_token = int(tokens[0].token_serial[8:])
        end_token = int(tokens[num-1].token_serial[8:])
        first_token_id = tokens[0].id
    except:
        first_token_id = 0
        st = 0
        last_ck = 0
        start_token = 0
        end_token = 0

    if total_pgs <= 17:
        meta_pg = 1
    elif total_pgs <= 43:
        meta_pg = 2
    elif total_pgs > 43:
        meta_pg = 3

    for i in range(total_pgs):
        if st + 9 <= last_ck:
            ft = st + 9
        else:
            ft = (last_ck - st) + st
        token_index.append({"page":(i+1+meta_pg),"starting_token":st,"finish_token": ft,"count":(ft-st)+1})
        st = ft + 1
    
    dt = now()

    context = {
        "num": num,
        "event": event,
        "tokens": tokens,
        "start_token": start_token,
        "end_token": end_token,
        "token_index": token_index,
        "total_pgs": total_pgs+meta_pg,
        "dt": dt,
        "first_token_id" : first_token_id
    }
    return render(request,"print_tokens.html",context)

@admin_access
def generate_tokens(request):
    if request.method == "POST":
        data = json.loads(request.body)
        num = data['num']
        event_id = data['event_id']
        event = Event.objects.get(id=event_id)

        bulk_list = list()

        check_existing_tokens= Token.objects.filter(event = event).order_by('-id')[:1]
        event_id_token = int(event_id) + 100
        tmp = 10000

        if len(check_existing_tokens) > 0:
            tmp = int(check_existing_tokens[0].token_serial[8:])

        num = int(num)
        if num > 300:
            num = 300

        # Token usage
        if(event.token_usage == 1):
            food_flag = True
            entry_flag = False
        if(event.token_usage == 2):
            food_flag = True
            entry_flag = True

        for i in range(num):
            tmp = tmp + 1
            token_sr = 'CSE-'+ str(event_id_token) + '-' + str(tmp)
            bulk_list.append(
                Token(event=event,token_serial = token_sr,food_flag =food_flag, entry_flag = entry_flag)
            )
        Token.objects.bulk_create(bulk_list)
    return JsonResponse({"msg":"Ok"}, safe=False)

@admin_access
def update_print_status(request):
    if request.method == "POST":
        data = json.loads(request.body)
        num = data['total_tokens']
        starting_token_id = data['s_token_id']
        ending_token_id = int(starting_token_id) + int(num)

        for i in range(int(starting_token_id),ending_token_id):
            token = Token.objects.get(id=i)
            token.is_printed = True
            token.save()

    return JsonResponse({"msg":"Done"}, safe=False)

@login_required
def scanner_dist(request, pk):
    event = Event.objects.get(id=pk)
    context = {
        "event": event
    }
    return render(request, "scanner_dist.html",context)

@login_required
def scanner_receive(request, pk):
    event = Event.objects.get(id=pk)
    context = {
        "event": event
    }
    return render(request, "scanner_receive.html",context)

@login_required
def token_activate(request):
    if request.method == "POST":
        data = json.loads(request.body)
        code = data['code']
        stu_id = data['stu_id']
        event_id = data['event_id']

        event = Event.objects.get(id = event_id)
        msg = "404"
        stu = ""
        try:
            stu = StudentList.objects.get(student_id = stu_id,event = event)
            if stu.claimed == True:
                msg = "303"
                return JsonResponse({"msg":msg}, safe=False)
        except:
            msg = "304"
            return JsonResponse({"msg":msg}, safe=False)
        try:
            # token = Token.objects.get(token_serial='CSE-101-10005',event=event,is_printed=True)
            token = Token.objects.get(token_serial=code,event=event,is_printed=True)
            if token.is_activated == True:
                msg = "403"
            else:
                msg = "200"
                token.student_id = stu_id
                token.is_activated = True
                token.save()
                stu.claimed = True
                stu.save()
            return JsonResponse({"msg":msg}, safe=False)
        except:
            return JsonResponse({"msg":msg}, safe=False)
    return JsonResponse({"msg":"No permission"}, safe=False)

@login_required
def token_activate_new(request):
    if request.method == "POST":
        data = json.loads(request.body)
        event_id = data['event_id']
        code = data['code']
        stu_id = data['stu_id']
        name = data['name']

        event = Event.objects.get(id = event_id)
        msg = "404"
        try:
            # token = Token.objects.get(token_serial="2051",event=event,is_printed=True)
            token = Token.objects.get(token_serial=code,event=event,is_printed=True)
            if token.is_activated == True:
                msg = "403"
            else:
                msg = "200"
                token.student_id = stu_id
                token.is_activated = True
                token.save()
                StudentList.objects.create(
                    name = name,
                    student_id = stu_id,
                    event = event,
                    claimed = True
                )
            return JsonResponse({"msg":msg}, safe=False)
        except:
            return JsonResponse({"msg":msg}, safe=False)
    return JsonResponse({"msg":"No permission"}, safe=False)
            
@login_required
def token_receive(request):
    if request.method == "POST":
        data = json.loads(request.body)
        code = data['code']
        event_id = data['event_id']
        tag = data['tag']
        msg = "404"
        event = Event.objects.get(id = event_id)
        try:
            token = Token.objects.get(token_serial=code,event=event,is_printed=True)
            # token = Token.objects.get(token_serial="CSE-101-10005",event=event,is_printed=True)
            if token.is_activated == False:
                msg = "403"
                return JsonResponse({"msg":msg}, safe=False)
            else:
                if int(tag) == 2:
                    if token.food_flag == False:
                        msg = "402"
                        return JsonResponse({"msg":msg}, safe=False)
                    else:
                        token.food_flag = False
                        msg = "202"
                        token.save()
                        return JsonResponse({"msg":msg}, safe=False)
                elif int(tag) == 1:
                    if token.entry_flag == False:
                        msg = "401"
                        return JsonResponse({"msg":msg}, safe=False)
                    else:
                        token.entry_flag = False
                        msg = "201"
                        token.save()
                        return JsonResponse({"msg":msg}, safe=False)
        except:
            return JsonResponse({"msg":msg}, safe=False)
    return JsonResponse({"msg":"No permission"}, safe=False)

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock title %}</title>
    <link rel="shortcut icon" href="https://th.bing.com/th/id/R.9022450cb9bd5c25aa83792341c1d93e?rik=pyPsMUjo7%2fTeLg&riu=http%3a%2f%2fcse.iubat.edu%2fwp-content%2fuploads%2f2019%2f06%2fiubat_cse-logo.png&ehk=EDxgn3M75GwbAI3b1Fwn7FLCfXN4NLEy3HGYtpFFQO8%3d&risl=&pid=ImgRaw&r=0" type="image/x-icon">

    
    <link href='https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css' rel='stylesheet'>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body>
    {% include 'nav.html' %}
    <nav aria-label="breadcrumb" class="container mt-4">
        <ol class="breadcrumb">
        {% block bc %}
        {% endblock bc %}
        </ol>
    </nav>
    {% block body %}{% endblock body %}
    {% include 'footer.html' %}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    {% block scripts %}{% endblock scripts %}
</body>
</html>

templates/dashboard_admin.html
{% extends 'base.html' %}
{% load static %}

{% block title %}{{user.username}}{% endblock title %}

{% block bc %}
<li class="breadcrumb-item">Dashboard</li>
{% endblock bc %}

{% block body %}
<div class="main">
    <div class="container">
        <h1 class="title_header">Hello {{user.name}}</h1>
        <div class="row text-center mb-4 justify-content-center">
            <a href="{% url 'account_settings' %}" class="btn btn-outline-secondary col-4 rounded-pill" style="display: flex; column-gap: 0.5rem; align-items: center; justify-content: center;"><i class='bx bx-cog text-dark-100 fs-4'></i> Account Settings</a>
        </div>
        <div id="notification">
            {% if user_deleted %}
                <div class="alert alert-success" role="alert">
                    <p class="mb-0">{{user_deleted}}</p>
                </div>
            {% endif %}
        </div>
        <div class="main_body px-4">
            <div class="row mb-4">
                <h3 class="text-center mb-4">All events</h3>
                <div class="text-center">
                    <a href="{% url 'events' %}" class="btn btn-primary">Go to all events page</a>
                </div>
                <div class="row mt-4 gap-2 justify-content-between">
                    <div class="col-md-8  border border-gray">
                        <h4 class="text-center">All Executives</h4>
                        <div class="users_list">
                            {% for user in all_users %}
                                <div class="row text-center">
                                    <span class="col d-flex align-items-center justify-content-center">{{user.username}}</span>
                                    <form class="col" method="post" action="delete_user">
                                        {% csrf_token %}
                                        <input type="hidden" value="{{user.id}}" name="id">
                                        <button type="submit" class="btn text-danger cursor-pointer" title="Remove User"><i class='bx bxs-x-circle fs-6'></i></button>
                                    </form>
                                </div>
                            {% endfor %}
                        </div>
                    </div>
                    <div class="col-md-3">
                        <h4 class="text-center">Quick Links</h4>
                        <div class="row gap-2">
                            <a href="{% url 'create_user' %}" class="btn btn-primary">Add New User</a>
                            <a href="{% url 'create_event' %}" class="btn btn-primary">Add New Event</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock body %}

templates/error.html
{% extends 'base.html' %}

{% block body %}
<div class="text-center">
    <h1>{{msg}}</h1>
    <div class="redirect">
        <a href="{% url 'index' %}">Go to homepage</a>
    </div>
</div>    

{% endblock body %}

templates/event_admin.html
{% extends 'base.html' %}
{% load static %}

{% block title %}{{event.name}}{% endblock title %}

{% block bc %}
<li class="breadcrumb-item active"><a href="{% url 'events' %}">Events</a></li>
<li class="breadcrumb-item">Event Details</li>
{% endblock bc %}

{% block body %}
<div class="main">
    <div class="container">
        <h1 class="title_header">Event Details</h1>
        <div class="main_body px-4">
            <div class="row text-lg-center">
                <p class="text-success fw-bold lead">{{token_status}}</p>
            </div>
            <div class="row">
                <div class="col-lg-6">
                    <p class="fw-bold lead">Event Name: <span class="lead fw-normal">{{event.name}}</span></p>
                </div>
                <div class="col-lg-6">
                    <p class="fw-bold lead">Event Date: 
                        <span class="lead fw-normal">
                            {% if event.event_date is not null %}
                            {{event.event_date|date:"D d M Y"}}
                            {% else %}
                            TBD
                            {% endif %} 
                        </span>
                    </p>
                </div>
            </div>
            <div class="row">
                <p class="fw-bold lead">Event Details: 
                    <span class="lead fw-normal">
                        {% if event.desc is not null %}
                        {{event.desc}}
                        {% else %}
                        TBD
                        {% endif %} 
                    </span>
                </p>
            </div>
            <div class="row">
                <div class="col-lg-6">
                    <p class="fw-bold lead">Token Distribution Start: 
                        <span class="lead fw-normal">
                            {% if event.token_dist_start is not null %}
                            {{event.token_dist_start}}
                            {% else %}
                            TBD
                            {% endif %} 
                        </span>
                    </p>
                </div>
                <div class="col-lg-6">
                    <p class="fw-bold lead">Token Distribution End: 
                        <span class="lead fw-normal">
                        {% if event.token_dist_end is not null %}
                        {{event.token_dist_end}}
                        {% else %}
                        TBD
                        {% endif %} 
                        </span>
                    </p>
                </div>
            </div>
            <div class="row">
                <p class="fw-bold lead">Distribution Place: 
                    <span class="fw-normal lead">
                        {% if event.distribution_place is not null %}
                        {{event.distribution_place}}
                        {% else %}
                        TBD
                        {% endif %} 
                    </span>
                </p>
            </div>
        </div>
        <h3 class="mt-4 text-center">Event Management - Admin level</h3>
        <div class="main_body mt-4 px-4">
            <form method="post" id="event_update_form" action="/event_update/" enctype='multipart/form-data'>
                {% csrf_token %}
                <div class="row">
                    <div class="lead fw-normal">
                        <label for="name" class="form-label fw-bold">Event Name</label>
                        <input type="text" class="form-control" id="name" name="name" value="{{event.name}}">
                    </div>
                </div>
                <div class="row mt-2">
                    <div class="lead">
                        <label for="place" class="form-label fw-bold">Token Distribution Place</label>
                        <input type="text" class="form-control" id="place" name="place" value="{{event.distribution_place}}">
                    </div>
                </div>
                <div class="row mt-2">
                    <div class="col-md-6 lead">
                        <label for="date" class="form-label fw-bold">Event Date</label>
                        <input type="date" class="form-control" id="date" name="date" value="{{event.event_date|date:'Y-m-d'}}">
                    </div>
                    <div class="col-md-6 lead">
                        <label for="time" class="form-label fw-bold">Event Starting Time</label>
                        <input type="time" class="form-control" id="time" name="time" value="{{event.event_date|date:'H:m'}}">
                    </div>
                </div>
                <div class="row mt-2">
                    <div class="col-md-6 lead">
                        <label for="token_start_date" class="form-label fw-bold">Token Distribution Start Date</label>
                        <input type="date" class="form-control" id="token_start_date" name="token_start_date" value="{{event.token_dist_start|date:'Y-m-d'}}">
                    </div>
                    <div class="col-md-6 lead">
                        <label for="token_start_time" class="form-label fw-bold">Token Distribution Start Time</label>
                        <input type="time" class="form-control" id="token_start_time" name="token_start_time" value="{{event.token_dist_start|date:'H:m'}}">
                    </div>
                </div>
                <div class="row mt-2">
                    <div class="col-md-6 lead">
                        <label for="token_end_date" class="form-label fw-bold">Token Distribution End Date</label>
                        <input type="date" class="form-control" id="token_end_date" name="token_end_date" value="{{event.token_dist_end|date:'Y-m-d'}}">
                    </div>
                    <div class="col-md-6 lead">
                        <label for="token_end_time" class="form-label fw-bold">Token Distribution End Time</label>
                        <input type="time" class="form-control" id="token_end_time" name="token_end_time" value="{{event.token_dist_end|date:'H:m'}}">
                    </div>
                </div>
                <div class="row mt-2">
                    <div class="lead">
                        <label for="desc" class="form-label fw-bold">Event Descriptopn</label>
                        <textarea name="desc" id="desc" rows="5" class="form-control">{{event.desc}}</textarea>
                    </div>               
                </div>
                <div class="row mt-2">
                    <div class="lead col-md-6">
                        <label for="usage" class="form-label fw-bold">Token Usage Limit</label>
                        <input type="number" class="form-control" value="{{event.token_usage}}" id="usage" name="usage">
                        <span class="fw-bold text-secondary" style="font-size: 14px;">*Maximum number of times one token can be redeemed.</span>
                        <br>
                        <span class="fw-bold text-danger" style="font-size: 14px;">*If you change the usage than all previous tokens will be updated. This can take a while.</span>
                        <br>
                        <span class="fw-bold text-secondary" style="font-size: 14px;">*Currently maximum token usage based on the architecture -> 2</span>
                    </div>               
                    <div class="lead col-md-6">
                        <label for="tags" class="form-label fw-bold">Token usage purposes</label>
                          <br>
                          <span class="fw-bold text-primary">*If token usage is 1 than the token will only act as food token.</span>
                          <br>
                          <span class="fw-bold text-primary">*If token usage is 2 than the token will act as entry and food token.</span>
                          <br>
                    </div>               
                </div>
                <div class="row mt-2">
                    <div class="lead col-md-6">
                        <label for="users" class="form-label fw-bold">Assign Executives</label>
                        <select class="form-select" aria-label="Assign Executives" id="users" name="users" multiple>
                            <optgroup label="Selected">
                                {% if epall.count > 0 %}
                                    {% for user in epall%}                               
                                        <option selected value="{{user.user.id}}">{{user.user.name}} - {{user.user.username}}</option>
                                    {% endfor %}                          
                                    {% else %}
                                    <option value="None" >No Executive Selected</option>
                                {% endif %}
                                </optgroup>
                                <optgroup label="All Executives">
                                {% for user in users %}
                                         <option value="{{user.id}}">{{user.name}} - {{user.username}}</option>
                                {% endfor %}
                                </optgroup>
                          </select>
                    </div>               
                    <div class="lead col-md-6 mt-2">
                        <div class="token_hanlde">
                            <h5 class="fw-bold">Manage Tokens <span class="text-primary">(Overview)</span></h5>
                            <p class="mb-0 fw-normal">Total tokens generated - <span class="fw-bold">{{event.get_tokens.count}}</span> </p>
                            <p class="mb-0 fw-normal">Total tokens printed - <span class="fw-bold">{{event.get_printed_tokens.count}}</span></p>
                            <p class="mb-0 fw-normal">Total tokens activated - <span class="fw-bold">{{event.get_activated_tokens.count}}</span></p>
                            <a href="{% url 'tokens:token_event' event.id%}" class="btn btn-sm btn-secondary w-100 mt-2">Token Management</a>
                        </div>
                    </div>               
                </div>
                <input type="hidden" value="{{event.id}}" name="pk">
                <div class="row px-2 gap-2 justify-content-center mt-4">
                    <button type="submit" class="btn btn-primary col-lg-4" id="update_btn">Update</button>
                    <button class="btn btn-danger col-lg-4" id="del_btn">Delete</button>
                </div>
            </form>
        </div>
        <h3 class="mt-4 text-center">Manage student list for {{event.name}}</h3>
        <div class="main_body mt-4 px-4">
            <div class="row justify-content-center text-center">
                {% if stu_list > 0 %}
                    <span class="fw-bold text-success">Student list uploaded with {{stu_list}} records.</span>
                    {% else %}
                    <span class="fw-bold text-secondary">Student list not uploaded.</span>
                {% endif %}
                <a href="{% url 'studentlist' event.id %}" class="btn btn-primary col-md-6 mt-2">Go to student list management</a>
            </div>
        </div>
    </div>
</div>
{% endblock body %}

{% block scripts %}
<script>
    let eventUpdateBtn = document.getElementById("update_btn"),
    delBtn = document.querySelector("#del_btn");

    const csrf = document.getElementsByName('csrfmiddlewaretoken')[0].value;

    const spinner = () => {
        return `
            <span class="spinner-border spinner-border-sm" role="status" aria-hidden="true"></span>
            `;
    }

    eventUpdateBtn.addEventListener("click",(e)=>{
        e.preventDefault();
        
        eventUpdateBtn.setAttribute("disabled", true);
        delBtn.setAttribute("disabled", true);
        eventUpdateBtn.innerHTML = spinner();

        setTimeout(() => {
            document.querySelector("#event_update_form").submit();
        }, 2000);
    });
    delBtn.addEventListener("click", (e) =>{
        e.preventDefault();
        eventUpdateBtn.setAttribute("disabled", true);
        delBtn.setAttribute("disabled", true);
        delBtn.innerHTML = spinner();
        
        fetch("/delete_event/", {
                method: 'POST',
                headers: {
                    'Content-Type': 'application/json',
                    'X-CSRFToken': csrf,
                },
                body: JSON.stringify({'event_id': "{{event.id}}" })
            })
            .then(async (response) => {
                let res = await response.json();
                window.location = "/dashboard/";
            })
            .catch(err => {
                console.log("Error");
                console.log(err)
            });
    });
</script>
{% endblock scripts %}